# Generated by Django 4.1.13 on 2024-04-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOT', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('mssv', models.OneToOneField(db_column='mssv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MOT.sinhvien')),
                ('diemgk', models.FloatField(blank=True, null=True)),
                ('diemck', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diem',
                'managed': False,
            },
        ),
    ]
